import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image
import tensorflow as tf

SUPPORTED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}
DEFAULT_THRESHOLD = 0.55


def load_class_names(class_config_path: str = "classes.json") -> list[str]:
    config_path = Path(class_config_path)
    if not config_path.exists():
        raise FileNotFoundError(f"Class config file not found: {config_path}")

    with open(config_path, "r", encoding="utf-8") as fh:
        config = json.load(fh)

    labels = config.get("labels") or {}
    if not labels:
        raise ValueError("No labels were found in the class configuration.")

    ordered = [labels[str(i)] for i in sorted((int(k) for k in labels.keys()))]
    return ordered


def parse_label(label: str):
    label = str(label).strip()
    if not label:
        return "Unknown", "Unknown"

    if "_" not in label:
        return label.replace("_", " ").title(), "Unknown"

    parts = label.split("_")
    produce_name = "_".join(parts[:-1])
    freshness = parts[-1].lower()

    freshness_map = {
        "fresh": "Fresh",
        "moderately_fresh": "Moderately Fresh",
        "moderatelyfresh": "Moderately Fresh",
        "rotten": "Rotten",
        "spoiled": "Rotten",
    }

    return produce_name.replace("_", " ").title(), freshness_map.get(freshness, freshness.title())


def validate_image_path(image_path: str | Path) -> Path:
    path = Path(image_path)
    if not path.exists() or not path.is_file():
        raise FileNotFoundError(f"Image file not found: {path}")
    if path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        raise ValueError(f"Unsupported file type for image: {path}")
    return path


def preprocess_image(image_path: str | Path, target_size=(224, 224)) -> np.ndarray:
    image = Image.open(str(image_path)).convert("RGB")
    image = image.resize(target_size)
    array = np.asarray(image, dtype=np.float32) / 255.0
    return np.expand_dims(array, axis=0)


def predict_image(
    image_path: str,
    model_path: str = "ml/models/freshness_model.keras",
    class_config_path: str = "classes.json",
    threshold: float = DEFAULT_THRESHOLD,
) -> dict:
    image_file = validate_image_path(image_path)
    model_file = Path(model_path)
    if not model_file.exists():
        raise FileNotFoundError(f"Model file not found: {model_file}")

    class_names = load_class_names(class_config_path)
    model = tf.keras.models.load_model(str(model_file))
    image_batch = preprocess_image(image_file)
    probabilities = model.predict(image_batch, verbose=0)
    confidence = float(np.max(probabilities[0]))
    predicted_index = int(np.argmax(probabilities[0]))
    predicted_label = class_names[predicted_index]
    produce_name, freshness_status = parse_label(predicted_label)

    if confidence < threshold:
        return {
            "produce": None,
            "category": None,
            "freshness": "Unknown",
            "confidence": round(confidence, 4),
            "model_version": "v1.0",
            "message": "Unsupported or low-confidence image",
            "predicted_label": predicted_label,
        }

    result = {
        "produce": produce_name,
        "category": None,
        "freshness": freshness_status if freshness_status != "Unknown" else "Unknown",
        "confidence": round(confidence, 4),
        "model_version": "v1.0",
        "message": "Prediction generated by the trained model.",
        "predicted_label": predicted_label,
    }
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Predict produce and freshness from an image using the trained model.")
    parser.add_argument("--image", type=str, required=True, help="Path to the input image file.")
    parser.add_argument("--model-path", type=str, default="ml/models/freshness_model.keras", help="Path to the trained model.")
    parser.add_argument("--class-config", type=str, default="classes.json", help="Path to the generated class config.")
    parser.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD, help="Probability threshold for unknown/unsupported images.")
    args = parser.parse_args()

    result = predict_image(
        image_path=args.image,
        model_path=args.model_path,
        class_config_path=args.class_config,
        threshold=args.threshold,
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
